// Auto-generated from Montreal_Weekenders_Restaurant_Guide_FULL.xlsx
window.RESTAURANTS = [
  {
    "id": "le-9ieme-ile-de-france",
    "name": "Le 9ième – Île de France",
    "cuisine": "French",
    "vibe": "Elegant",
    "description": "Classic Parisian-inspired dining experience",
    "bestFor": "Corporate dinners",
    "clientLevel": 5,
    "rating": 4.7,
    "neighborhood": "Downtown",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "annette",
    "name": "Annette",
    "cuisine": "French Bistro",
    "vibe": "Cozy",
    "description": "Neighborhood-style French cuisine",
    "bestFor": "Casual client lunch",
    "clientLevel": 4,
    "rating": 4.3,
    "neighborhood": "Saint-Henri",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "au-coin",
    "name": "Au Coin",
    "cuisine": "French Bistro",
    "vibe": "Casual",
    "description": "Relaxed atmosphere with seasonal dishes",
    "bestFor": "Date night",
    "clientLevel": 4,
    "rating": 4.2,
    "neighborhood": "Little Burgundy",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "bar-bara",
    "name": "Bar Bara",
    "cuisine": "Wine Bar",
    "vibe": "Trendy",
    "description": "Natural wine and shareable plates",
    "bestFor": "Cocktails",
    "clientLevel": 4,
    "rating": 4.4,
    "neighborhood": "Plateau",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "bel-george",
    "name": "Bel George",
    "cuisine": "Steakhouse",
    "vibe": "Luxury",
    "description": "High-end steakhouse inside Le Mount Stephen",
    "bestFor": "Executive dinners",
    "clientLevel": 5,
    "rating": 4.7,
    "neighborhood": "Downtown",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "bar-st-denis",
    "name": "Bar St-Denis",
    "cuisine": "Wine Bar",
    "vibe": "Hip",
    "description": "Creative wine bar with seasonal menu",
    "bestFor": "Friends & wine",
    "clientLevel": 4,
    "rating": 4.5,
    "neighborhood": "Plateau",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "barroco",
    "name": "Barroco",
    "cuisine": "Spanish / Mediterranean",
    "vibe": "Romantic",
    "description": "Old Montreal staple with tapas and seafood",
    "bestFor": "Client entertainment",
    "clientLevel": 5,
    "rating": 4.6,
    "neighborhood": "Old Montreal",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "beba",
    "name": "Beba",
    "cuisine": "Argentinian",
    "vibe": "Warm",
    "description": "Modern Argentinian cuisine with natural wines",
    "bestFor": "Foodies",
    "clientLevel": 5,
    "rating": 4.8,
    "neighborhood": "Verdun",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "bouillon-albert",
    "name": "Bouillon Albert",
    "cuisine": "Steakhouse",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its steakhouse menu and cozy atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 4,
    "rating": 4.5,
    "neighborhood": "Verdun",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "bouillon-bilk",
    "name": "Bouillon Bilk",
    "cuisine": "Contemporary",
    "vibe": "Minimalist",
    "description": "Inventive fine dining tasting menus",
    "bestFor": "High-end clients",
    "clientLevel": 5,
    "rating": 4.8,
    "neighborhood": "Downtown",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "bowie-bar",
    "name": "Bowie (bar)",
    "cuisine": "Italian",
    "vibe": "Romantic",
    "description": "Popular Montreal spot known for its italian menu and romantic atmosphere.",
    "bestFor": "Client dinners",
    "clientLevel": 4,
    "rating": 4.3,
    "neighborhood": "Old Montreal",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "buvette-chez-simone",
    "name": "Buvette Chez Simone",
    "cuisine": "French Bistro",
    "vibe": "Casual Chic",
    "description": "Popular Montreal spot known for its french bistro menu and casual chic atmosphere.",
    "bestFor": "Team dinners",
    "clientLevel": 4,
    "rating": 4.5,
    "neighborhood": "Little Burgundy",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "cabaret-l-enfer",
    "name": "Cabaret l’enfer",
    "cuisine": "Italian",
    "vibe": "Romantic",
    "description": "Popular Montreal spot known for its italian menu and romantic atmosphere.",
    "bestFor": "Business lunch",
    "clientLevel": 5,
    "rating": 4.6,
    "neighborhood": "Old Montreal",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "cadet",
    "name": "Cadet",
    "cuisine": "Wine Bar",
    "vibe": "Casual Chic",
    "description": "Popular Montreal spot known for its wine bar menu and casual chic atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 5,
    "rating": 4.7,
    "neighborhood": "Westmount",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "cafe-ferreira",
    "name": "Café Ferreira",
    "cuisine": "Steakhouse",
    "vibe": "Upscale",
    "description": "Popular Montreal spot known for its steakhouse menu and upscale atmosphere.",
    "bestFor": "Casual meetings",
    "clientLevel": 5,
    "rating": 4.6,
    "neighborhood": "Plateau",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "cafe-parvis",
    "name": "Café Parvis",
    "cuisine": "Québécois",
    "vibe": "Modern",
    "description": "Popular Montreal spot known for its québécois menu and modern atmosphere.",
    "bestFor": "Team dinners",
    "clientLevel": 4,
    "rating": 4.7,
    "neighborhood": "Mile End",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "capisco",
    "name": "Capisco",
    "cuisine": "Contemporary",
    "vibe": "Romantic",
    "description": "Popular Montreal spot known for its contemporary menu and romantic atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 4,
    "rating": 4.2,
    "neighborhood": "Downtown",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "cappello",
    "name": "Cappello",
    "cuisine": "Steakhouse",
    "vibe": "Trendy",
    "description": "Popular Montreal spot known for its steakhouse menu and trendy atmosphere.",
    "bestFor": "Business lunch",
    "clientLevel": 3,
    "rating": 4.3,
    "neighborhood": "Little Burgundy",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "casavant",
    "name": "Casavant",
    "cuisine": "Contemporary",
    "vibe": "Upscale",
    "description": "Popular Montreal spot known for its contemporary menu and upscale atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 4,
    "rating": 4.6,
    "neighborhood": "Mile End",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "chez-delmo",
    "name": "Chez Delmo",
    "cuisine": "Cocktail Bar",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its cocktail bar menu and minimalist atmosphere.",
    "bestFor": "Team dinners",
    "clientLevel": 4,
    "rating": 4.7,
    "neighborhood": "Saint-Henri",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "club-chasse-et-peche",
    "name": "Club Chasse et Pêche",
    "cuisine": "Wine Bar",
    "vibe": "Casual Chic",
    "description": "Popular Montreal spot known for its wine bar menu and casual chic atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 5,
    "rating": 4.2,
    "neighborhood": "Little Burgundy",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "da-emma",
    "name": "Da Emma",
    "cuisine": "Mediterranean",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its mediterranean menu and cozy atmosphere.",
    "bestFor": "Wine lovers",
    "clientLevel": 3,
    "rating": 4.7,
    "neighborhood": "Verdun",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "damas",
    "name": "Damas",
    "cuisine": "Syrian / Middle Eastern",
    "vibe": "Upscale",
    "description": "Excellent tasting menus and sharing plates",
    "bestFor": "Luxury dinners",
    "clientLevel": 5,
    "rating": 4.9,
    "neighborhood": "Outremont",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "dorsia",
    "name": "Dorsia",
    "cuisine": "Mediterranean",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its mediterranean menu and minimalist atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 3,
    "rating": 4.3,
    "neighborhood": "Verdun",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "elena",
    "name": "Elena",
    "cuisine": "Wine Bar",
    "vibe": "Lively",
    "description": "Popular Montreal spot known for its wine bar menu and lively atmosphere.",
    "bestFor": "Team dinners",
    "clientLevel": 5,
    "rating": 4.5,
    "neighborhood": "Little Burgundy",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "estiatorio-milos",
    "name": "Estiatorio Milos",
    "cuisine": "Wine Bar",
    "vibe": "Modern",
    "description": "Popular Montreal spot known for its wine bar menu and modern atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 3,
    "rating": 4.4,
    "neighborhood": "Saint-Henri",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "ferme-bika",
    "name": "Ferme Bika",
    "cuisine": "Mediterranean",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its mediterranean menu and minimalist atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 3,
    "rating": 4.2,
    "neighborhood": "Plateau",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "fleurs-et-cadeaux",
    "name": "Fleurs et Cadeaux",
    "cuisine": "Cocktail Bar",
    "vibe": "Lively",
    "description": "Popular Montreal spot known for its cocktail bar menu and lively atmosphere.",
    "bestFor": "Team dinners",
    "clientLevel": 3,
    "rating": 4.6,
    "neighborhood": "Old Montreal",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "gia-vin-grill",
    "name": "Gia vin & grill",
    "cuisine": "Québécois",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its québécois menu and minimalist atmosphere.",
    "bestFor": "Team dinners",
    "clientLevel": 3,
    "rating": 4.7,
    "neighborhood": "Saint-Henri",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "hana-korean-steakhouse",
    "name": "Hana Korean Steakhouse",
    "cuisine": "Japanese",
    "vibe": "Lively",
    "description": "Popular Montreal spot known for its japanese menu and lively atmosphere.",
    "bestFor": "Casual meetings",
    "clientLevel": 4,
    "rating": 4.2,
    "neighborhood": "Verdun",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "heni",
    "name": "Heni",
    "cuisine": "Québécois",
    "vibe": "Elegant",
    "description": "Popular Montreal spot known for its québécois menu and elegant atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 3,
    "rating": 4.3,
    "neighborhood": "Little Burgundy",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "henrietta",
    "name": "Henrietta",
    "cuisine": "Contemporary",
    "vibe": "Modern",
    "description": "Popular Montreal spot known for its contemporary menu and modern atmosphere.",
    "bestFor": "Client dinners",
    "clientLevel": 4,
    "rating": 4.5,
    "neighborhood": "Downtown",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "hiatus",
    "name": "Hiatus",
    "cuisine": "Seafood",
    "vibe": "Trendy",
    "description": "Popular Montreal spot known for its seafood menu and trendy atmosphere.",
    "bestFor": "Casual meetings",
    "clientLevel": 3,
    "rating": 4.2,
    "neighborhood": "Little Burgundy",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "hidden-fish",
    "name": "Hidden Fish",
    "cuisine": "Italian",
    "vibe": "Casual Chic",
    "description": "Popular Montreal spot known for its italian menu and casual chic atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 4,
    "rating": 4.4,
    "neighborhood": "Little Burgundy",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "hogan-beaufort",
    "name": "Hogan & Beaufort",
    "cuisine": "Seafood",
    "vibe": "Casual Chic",
    "description": "Popular Montreal spot known for its seafood menu and casual chic atmosphere.",
    "bestFor": "Team dinners",
    "clientLevel": 5,
    "rating": 4.6,
    "neighborhood": "Downtown",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "ile-flottante",
    "name": "Île Flottante",
    "cuisine": "Wine Bar",
    "vibe": "Upscale",
    "description": "Popular Montreal spot known for its wine bar menu and upscale atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 3,
    "rating": 4.1,
    "neighborhood": "Westmount",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "jellyfish",
    "name": "Jellyfish",
    "cuisine": "Mediterranean",
    "vibe": "Casual Chic",
    "description": "Popular Montreal spot known for its mediterranean menu and casual chic atmosphere.",
    "bestFor": "Casual meetings",
    "clientLevel": 3,
    "rating": 4.6,
    "neighborhood": "Mile End",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "joe-beef",
    "name": "Joe Beef",
    "cuisine": "French / Québécois",
    "vibe": "Iconic",
    "description": "Legendary Montreal dining institution",
    "bestFor": "VIP clients",
    "clientLevel": 5,
    "rating": 4.9,
    "neighborhood": "Little Burgundy",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "juliette-plaza",
    "name": "Juliette Plaza",
    "cuisine": "Italian",
    "vibe": "Romantic",
    "description": "Popular Montreal spot known for its italian menu and romantic atmosphere.",
    "bestFor": "Business lunch",
    "clientLevel": 5,
    "rating": 4.2,
    "neighborhood": "Little Burgundy",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "jun-i",
    "name": "Jun I",
    "cuisine": "Japanese",
    "vibe": "Refined",
    "description": "High-end sushi omakase experience",
    "bestFor": "VIP clients",
    "clientLevel": 5,
    "rating": 4.8,
    "neighborhood": "Westmount",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "l-express",
    "name": "L’Express",
    "cuisine": "Italian",
    "vibe": "Trendy",
    "description": "Popular Montreal spot known for its italian menu and trendy atmosphere.",
    "bestFor": "Casual meetings",
    "clientLevel": 3,
    "rating": 4.6,
    "neighborhood": "Old Montreal",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "le-chien-fumant",
    "name": "Le Chien Fumant",
    "cuisine": "French Bistro",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its french bistro menu and cozy atmosphere.",
    "bestFor": "Business lunch",
    "clientLevel": 3,
    "rating": 4.3,
    "neighborhood": "Mile End",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "le-filet",
    "name": "Le Filet",
    "cuisine": "Seafood",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its seafood menu and cozy atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 3,
    "rating": 4.6,
    "neighborhood": "Little Burgundy",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "le-majestique",
    "name": "Le Majestique",
    "cuisine": "Contemporary",
    "vibe": "Lively",
    "description": "Popular Montreal spot known for its contemporary menu and lively atmosphere.",
    "bestFor": "Business lunch",
    "clientLevel": 5,
    "rating": 4.2,
    "neighborhood": "Westmount",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "le-mousso",
    "name": "Le Mousso",
    "cuisine": "Fine Dining",
    "vibe": "Avant-garde",
    "description": "Immersive tasting menu experience",
    "bestFor": "Special occasions",
    "clientLevel": 5,
    "rating": 4.9,
    "neighborhood": "Hochelaga",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "le-serpent",
    "name": "Le Serpent",
    "cuisine": "Italian",
    "vibe": "Industrial Chic",
    "description": "Stylish Italian restaurant in Old Montreal",
    "bestFor": "Group dinners",
    "clientLevel": 5,
    "rating": 4.7,
    "neighborhood": "Old Montreal",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "le-systeme",
    "name": "Le Système",
    "cuisine": "Italian",
    "vibe": "Romantic",
    "description": "Popular Montreal spot known for its italian menu and romantic atmosphere.",
    "bestFor": "Wine lovers",
    "clientLevel": 3,
    "rating": 4.5,
    "neighborhood": "Little Burgundy",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "le-velvet",
    "name": "Le Velvet",
    "cuisine": "Seafood",
    "vibe": "Lively",
    "description": "Popular Montreal spot known for its seafood menu and lively atmosphere.",
    "bestFor": "Client dinners",
    "clientLevel": 5,
    "rating": 4.5,
    "neighborhood": "Verdun",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "le-vin-papillon",
    "name": "Le Vin Papillon",
    "cuisine": "Steakhouse",
    "vibe": "Upscale",
    "description": "Popular Montreal spot known for its steakhouse menu and upscale atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 4,
    "rating": 4.1,
    "neighborhood": "Old Montreal",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "le-violon",
    "name": "Le Violon",
    "cuisine": "French",
    "vibe": "Intimate",
    "description": "Modern refined French cuisine",
    "bestFor": "Date night",
    "clientLevel": 5,
    "rating": 4.7,
    "neighborhood": "Plateau",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "lemeac",
    "name": "Leméac",
    "cuisine": "Seafood",
    "vibe": "Romantic",
    "description": "Popular Montreal spot known for its seafood menu and romantic atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 5,
    "rating": 4.4,
    "neighborhood": "Plateau",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "limousine",
    "name": "Limousine",
    "cuisine": "French Bistro",
    "vibe": "Romantic",
    "description": "Popular Montreal spot known for its french bistro menu and romantic atmosphere.",
    "bestFor": "Casual meetings",
    "clientLevel": 3,
    "rating": 4.3,
    "neighborhood": "Saint-Henri",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "liverpool-house",
    "name": "Liverpool House",
    "cuisine": "French / Québécois",
    "vibe": "Lively",
    "description": "Classic Montreal comfort food and wine",
    "bestFor": "Business dinners",
    "clientLevel": 5,
    "rating": 4.8,
    "neighborhood": "Little Burgundy",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "lumi",
    "name": "Lumi",
    "cuisine": "Cocktail Bar",
    "vibe": "Casual Chic",
    "description": "Popular Montreal spot known for its cocktail bar menu and casual chic atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 3,
    "rating": 4.5,
    "neighborhood": "Mile End",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "maison-boulud",
    "name": "Maison Boulud",
    "cuisine": "French",
    "vibe": "Luxury",
    "description": "Refined French cuisine at Ritz-Carlton",
    "bestFor": "Luxury clients",
    "clientLevel": 5,
    "rating": 4.8,
    "neighborhood": "Golden Square Mile",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "mano-cornuto",
    "name": "Mano Cornuto",
    "cuisine": "Contemporary",
    "vibe": "Upscale",
    "description": "Popular Montreal spot known for its contemporary menu and upscale atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 4,
    "rating": 4.6,
    "neighborhood": "Verdun",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "marci",
    "name": "Marci",
    "cuisine": "Italian",
    "vibe": "Elegant",
    "description": "Popular Montreal spot known for its italian menu and elegant atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 4,
    "rating": 4.6,
    "neighborhood": "Little Burgundy",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "marcus",
    "name": "Marcus",
    "cuisine": "Contemporary",
    "vibe": "Chic",
    "description": "Luxury hotel restaurant with vibrant atmosphere",
    "bestFor": "Business lunches",
    "clientLevel": 5,
    "rating": 4.6,
    "neighborhood": "Downtown",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "mare",
    "name": "Mare",
    "cuisine": "Wine Bar",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its wine bar menu and cozy atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 3,
    "rating": 4.4,
    "neighborhood": "Saint-Henri",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "mastard",
    "name": "Mastard",
    "cuisine": "Mediterranean",
    "vibe": "Lively",
    "description": "Popular Montreal spot known for its mediterranean menu and lively atmosphere.",
    "bestFor": "Wine lovers",
    "clientLevel": 5,
    "rating": 4.4,
    "neighborhood": "Westmount",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "matu",
    "name": "Matú",
    "cuisine": "Seafood",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its seafood menu and minimalist atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 4,
    "rating": 4.5,
    "neighborhood": "Mile End",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "mckiernan",
    "name": "McKiernan",
    "cuisine": "Contemporary",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its contemporary menu and cozy atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 4,
    "rating": 4.3,
    "neighborhood": "Verdun",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "miracolo",
    "name": "Miracolo",
    "cuisine": "Mediterranean",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its mediterranean menu and cozy atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 3,
    "rating": 4.3,
    "neighborhood": "Verdun",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "moccione",
    "name": "Moccione",
    "cuisine": "Italian",
    "vibe": "Cozy",
    "description": "Known for handmade pasta and intimate vibe",
    "bestFor": "Italian lovers",
    "clientLevel": 5,
    "rating": 4.7,
    "neighborhood": "Villeray",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "moishes",
    "name": "Moishes",
    "cuisine": "Contemporary",
    "vibe": "Modern",
    "description": "Popular Montreal spot known for its contemporary menu and modern atmosphere.",
    "bestFor": "Client dinners",
    "clientLevel": 3,
    "rating": 4.4,
    "neighborhood": "Westmount",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "molenne",
    "name": "Molenne",
    "cuisine": "Cocktail Bar",
    "vibe": "Lively",
    "description": "Popular Montreal spot known for its cocktail bar menu and lively atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 5,
    "rating": 4.3,
    "neighborhood": "Westmount",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "mon-lapin",
    "name": "Mon Lapin",
    "cuisine": "Wine Bar",
    "vibe": "Trendy",
    "description": "Natural wine destination with seasonal dishes",
    "bestFor": "Foodie clients",
    "clientLevel": 5,
    "rating": 4.9,
    "neighborhood": "Little Italy",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "monarque",
    "name": "Monarque",
    "cuisine": "French",
    "vibe": "Elegant",
    "description": "Upscale brasserie and fine dining",
    "bestFor": "Client dinners",
    "clientLevel": 5,
    "rating": 4.8,
    "neighborhood": "Old Montreal",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "montreal-plaza",
    "name": "Montreal Plaza",
    "cuisine": "Steakhouse",
    "vibe": "Modern",
    "description": "Popular Montreal spot known for its steakhouse menu and modern atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 3,
    "rating": 4.3,
    "neighborhood": "Westmount",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "nama-omakase",
    "name": "Nama Omakase",
    "cuisine": "Italian",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its italian menu and minimalist atmosphere.",
    "bestFor": "Casual meetings",
    "clientLevel": 5,
    "rating": 4.1,
    "neighborhood": "Little Burgundy",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "nora-gray",
    "name": "Nora Gray",
    "cuisine": "Japanese",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its japanese menu and cozy atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 3,
    "rating": 4.4,
    "neighborhood": "Mile End",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "numero-bar",
    "name": "Numéro (bar)",
    "cuisine": "Québécois",
    "vibe": "Romantic",
    "description": "Popular Montreal spot known for its québécois menu and romantic atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 3,
    "rating": 4.3,
    "neighborhood": "Old Montreal",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "oncle-lee",
    "name": "Oncle Lee",
    "cuisine": "Seafood",
    "vibe": "Elegant",
    "description": "Popular Montreal spot known for its seafood menu and elegant atmosphere.",
    "bestFor": "Wine lovers",
    "clientLevel": 3,
    "rating": 4.3,
    "neighborhood": "Verdun",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "papito",
    "name": "Papito",
    "cuisine": "Mediterranean",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its mediterranean menu and minimalist atmosphere.",
    "bestFor": "Business lunch",
    "clientLevel": 5,
    "rating": 4.2,
    "neighborhood": "Verdun",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "parapluie",
    "name": "Parapluie",
    "cuisine": "Japanese",
    "vibe": "Trendy",
    "description": "Popular Montreal spot known for its japanese menu and trendy atmosphere.",
    "bestFor": "Business lunch",
    "clientLevel": 3,
    "rating": 4.1,
    "neighborhood": "Downtown",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "parcelles",
    "name": "Parcelles",
    "cuisine": "Italian",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its italian menu and cozy atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 4,
    "rating": 4.6,
    "neighborhood": "Downtown",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "park",
    "name": "Park",
    "cuisine": "Japanese",
    "vibe": "Modern",
    "description": "Creative sushi and Japanese cuisine",
    "bestFor": "Sushi lovers",
    "clientLevel": 5,
    "rating": 4.7,
    "neighborhood": "Westmount",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "pichai",
    "name": "Pichai",
    "cuisine": "Italian",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its italian menu and cozy atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 4,
    "rating": 4.6,
    "neighborhood": "Verdun",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "place-carmin",
    "name": "Place Carmin",
    "cuisine": "Japanese",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its japanese menu and minimalist atmosphere.",
    "bestFor": "Business lunch",
    "clientLevel": 4,
    "rating": 4.4,
    "neighborhood": "Saint-Henri",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "restaurant-jerome-ferrer",
    "name": "Restaurant Jérôme Ferrer",
    "cuisine": "Steakhouse",
    "vibe": "Upscale",
    "description": "Popular Montreal spot known for its steakhouse menu and upscale atmosphere.",
    "bestFor": "Business lunch",
    "clientLevel": 3,
    "rating": 4.5,
    "neighborhood": "Westmount",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "romies",
    "name": "Romies",
    "cuisine": "Steakhouse",
    "vibe": "Romantic",
    "description": "Popular Montreal spot known for its steakhouse menu and romantic atmosphere.",
    "bestFor": "Team dinners",
    "clientLevel": 3,
    "rating": 4.2,
    "neighborhood": "Downtown",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "rotisserie-la-lune",
    "name": "Rôtisserie La Lune",
    "cuisine": "Japanese",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its japanese menu and cozy atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 3,
    "rating": 4.7,
    "neighborhood": "Plateau",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "sabayon",
    "name": "Sabayon",
    "cuisine": "Wine Bar",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its wine bar menu and minimalist atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 5,
    "rating": 4.4,
    "neighborhood": "Westmount",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "salle-climatisee",
    "name": "Salle Climatisée",
    "cuisine": "Contemporary",
    "vibe": "Modern",
    "description": "Popular Montreal spot known for its contemporary menu and modern atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 3,
    "rating": 4.4,
    "neighborhood": "Saint-Henri",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "salon-badin-bar",
    "name": "Salon Badin (bar)",
    "cuisine": "Steakhouse",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its steakhouse menu and minimalist atmosphere.",
    "bestFor": "Date night",
    "clientLevel": 3,
    "rating": 4.5,
    "neighborhood": "Mile End",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "siamo-noi",
    "name": "Siamo Noi",
    "cuisine": "Contemporary",
    "vibe": "Modern",
    "description": "Popular Montreal spot known for its contemporary menu and modern atmosphere.",
    "bestFor": "Team dinners",
    "clientLevel": 5,
    "rating": 4.4,
    "neighborhood": "Little Burgundy",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "stellina",
    "name": "Stellina",
    "cuisine": "Cocktail Bar",
    "vibe": "Upscale",
    "description": "Popular Montreal spot known for its cocktail bar menu and upscale atmosphere.",
    "bestFor": "Business lunch",
    "clientLevel": 4,
    "rating": 4.5,
    "neighborhood": "Verdun",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "subterra-bar",
    "name": "Subterra (bar)",
    "cuisine": "Italian",
    "vibe": "Elegant",
    "description": "Popular Montreal spot known for its italian menu and elegant atmosphere.",
    "bestFor": "Team dinners",
    "clientLevel": 5,
    "rating": 4.5,
    "neighborhood": "Plateau",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "sushi-nishinokaze",
    "name": "Sushi Nishinokaze",
    "cuisine": "French Bistro",
    "vibe": "Casual Chic",
    "description": "Popular Montreal spot known for its french bistro menu and casual chic atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 3,
    "rating": 4.3,
    "neighborhood": "Little Burgundy",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "taverne-atlantic",
    "name": "Taverne Atlantic",
    "cuisine": "Steakhouse",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its steakhouse menu and cozy atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 5,
    "rating": 4.6,
    "neighborhood": "Old Montreal",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "tiradito",
    "name": "Tiradito",
    "cuisine": "Seafood",
    "vibe": "Lively",
    "description": "Popular Montreal spot known for its seafood menu and lively atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 4,
    "rating": 4.6,
    "neighborhood": "Verdun",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "toque",
    "name": "Toqué",
    "cuisine": "Fine Dining",
    "vibe": "Classic",
    "description": "One of Montreal’s top gastronomic experiences",
    "bestFor": "Executive dining",
    "clientLevel": 5,
    "rating": 4.8,
    "neighborhood": "Downtown",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "tuck-shop",
    "name": "Tuck Shop",
    "cuisine": "Wine Bar",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its wine bar menu and cozy atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 4,
    "rating": 4.7,
    "neighborhood": "Plateau",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "vin-vin-vin",
    "name": "Vin vin vin",
    "cuisine": "Wine Bar",
    "vibe": "Fun",
    "description": "Natural wine and creative plates",
    "bestFor": "Wine nights",
    "clientLevel": 4,
    "rating": 4.5,
    "neighborhood": "Plateau",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "willie-s-clubhouse",
    "name": "Willie’s Clubhouse",
    "cuisine": "Cocktail Bar",
    "vibe": "Trendy",
    "description": "Popular Montreal spot known for its cocktail bar menu and trendy atmosphere.",
    "bestFor": "Casual meetings",
    "clientLevel": 4,
    "rating": 4.3,
    "neighborhood": "Verdun",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "yama",
    "name": "Yama",
    "cuisine": "Québécois",
    "vibe": "Elegant",
    "description": "Popular Montreal spot known for its québécois menu and elegant atmosphere.",
    "bestFor": "Cocktails",
    "clientLevel": 4,
    "rating": 4.1,
    "neighborhood": "Plateau",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "yubari-bar",
    "name": "Yubari (bar)",
    "cuisine": "Japanese",
    "vibe": "Lively",
    "description": "Popular Montreal spot known for its japanese menu and lively atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 5,
    "rating": 4.4,
    "neighborhood": "Verdun",
    "price": "$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "savio-volpe",
    "name": "Savio Volpe",
    "cuisine": "Contemporary",
    "vibe": "Modern",
    "description": "Popular Montreal spot known for its contemporary menu and modern atmosphere.",
    "bestFor": "Wine lovers",
    "clientLevel": 5,
    "rating": 4.1,
    "neighborhood": "Plateau",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "homer-street-cafe",
    "name": "Homer Street Café",
    "cuisine": "French Bistro",
    "vibe": "Minimalist",
    "description": "Popular Montreal spot known for its french bistro menu and minimalist atmosphere.",
    "bestFor": "Foodies",
    "clientLevel": 5,
    "rating": 4.6,
    "neighborhood": "Downtown",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "myers",
    "name": "Myers",
    "cuisine": "Cocktail Bar",
    "vibe": "Cozy",
    "description": "Popular Montreal spot known for its cocktail bar menu and cozy atmosphere.",
    "bestFor": "Casual meetings",
    "clientLevel": 4,
    "rating": 4.6,
    "neighborhood": "Downtown",
    "price": "$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  },
  {
    "id": "dandy",
    "name": "Dandy",
    "cuisine": "Québécois",
    "vibe": "Lively",
    "description": "Popular Montreal spot known for its québécois menu and lively atmosphere.",
    "bestFor": "Client dinners",
    "clientLevel": 5,
    "rating": 4.3,
    "neighborhood": "Verdun",
    "price": "$$$$",
    "notes": "Great option to keep on your Montreal client recommendation list."
  }
];
